// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzVUcd3vEgARHfIUMi9tvTrrWGufdRZ1Q',
    appId: '1:767692358515:android:cb4c3374b273d31b48fb06',
    messagingSenderId: '767692358515',
    projectId: 'kipcount-95740',
    storageBucket: 'kipcount-95740.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXwgb6TYAFS_mEkEho7SgIhlwUGRr2BVc',
    appId: '1:767692358515:ios:cdeb4916f2c8b82348fb06',
    messagingSenderId: '767692358515',
    projectId: 'kipcount-95740',
    storageBucket: 'kipcount-95740.firebasestorage.app',
    iosBundleId: 'com.kipcount.kipcount',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_rFsBRS7BXnADunE3Bunxw60djYtL7h4',
    appId: '1:767692358515:web:d222450bab513d9948fb06',
    messagingSenderId: '767692358515',
    projectId: 'kipcount-95740',
    authDomain: 'kipcount-95740.firebaseapp.com',
    storageBucket: 'kipcount-95740.firebasestorage.app',
    measurementId: 'G-S1N1H2VJFF',
  );
}
